
format="""
[  $username ](bg:#bf616a fg:#d8dee9)\
[ ](bg:#d08770 fg:#bf616a)\
$directory\
[ ](bg:#EBCB8B fg:#d08770)\
[$git_branch $git_status](bg:#EBCB8B fg:#2E3440)\
[ ](bg:#2E3440 fg:#EBCB8B)\

\n$character
"""

right_format="""
"""

[username]
format="$user"
show_always=true

[directory]
style = "bg:#d08770 fg:#d8dee9"
format = "[󰉋 $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[git_branch]
format = "$symbol $branch"
symbol = ""

[git_status]
format = '($all_status$ahead_behind )'
ahead = '⇡${count}'
behind = '⇣${count}'
